import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('ru'),
    Locale('ja'),
  ];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String key) {
    final String languageCode = locale.languageCode;
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);

  String t(String key) => l10n.t(key);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (Locale supportedLocale) =>
          supportedLocale.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>>
_localizedValues = <String, Map<String, String>>{
  'en': <String, String>{
    'app_name': 'MiruShin',
    'app_tagline': 'Media command center',
    'Board': 'Board',
    'Discovery': 'Discovery',
    'Library': 'Library',
    'Calendar': 'Calendar',
    'Addons': 'Addons',
    'Settings': 'Settings',
    'More': 'More',
    'Switch Catalog Mode': 'Switch Catalog Mode',
    'Switch to': 'Switch to',
    'Current catalog': 'Current catalog',
    'Details': 'Details',
    'Add to Library': 'Add to Library',
    'Track Progress': 'Track Progress',
    'Mark as Watched': 'Mark as Watched',
    'Open Calendar': 'Open Calendar',
    'Manage Addons': 'Manage Addons',
    'Continue Later': 'Continue Later',
    'Popular Movies': 'Popular Movies',
    'Popular Series': 'Popular Series',
    'Popular Anime': 'Popular Anime',
    'Trending Now': 'Trending Now',
    'Recently Added to Library': 'Recently Added to Library',
    'Calendar Preview': 'Calendar Preview',
    'Quick Access': 'Quick Access',
    'Search media, genres, people, moods':
        'Search media, genres, people, moods',
    'All': 'All',
    'Movies': 'Movies',
    'Series': 'Series',
    'Anime': 'Anime',
    'Trending': 'Trending',
    'Popular': 'Popular',
    'Top Rated': 'Top Rated',
    'New Releases': 'New Releases',
    'Coming Soon': 'Coming Soon',
    'Genres': 'Genres',
    'Year': 'Year',
    'Rating': 'Rating',
    'Language': 'Language',
    'Sort by': 'Sort by',
    'Popularity': 'Popularity',
    'Release Date': 'Release Date',
    'Recently Updated': 'Recently Updated',
    'No Results Yet': 'No Results Yet',
    'Try a broader search or clear the active filters.':
        'Try a broader search or clear the active filters.',
    'Preview State': 'Preview State',
    'This is where loading and error states will appear.':
        'This is where loading and error states will appear.',
    'Local': 'Local',
    'Watchlist': 'Watchlist',
    'Favorites': 'Favorites',
    'Watched': 'Watched',
    'Custom Collections': 'Custom Collections',
    'Tracking Sync': 'Tracking Sync',
    'Connected Services': 'Connected Services',
    'Conflict Resolution': 'Conflict Resolution',
    'Import / Export': 'Import / Export',
    'Upcoming Episodes': 'Upcoming Episodes',
    'New Movie Releases': 'New Movie Releases',
    'Anime Airing Schedule': 'Anime Airing Schedule',
    'Library Related': 'Library Related',
    'Calendar data appears here when available.':
        'Calendar data appears here when available.',
    'Today': 'Today',
    'Month': 'Month',
    'Week': 'Week',
    'List': 'List',
    'Library Only': 'Library Only',
    'Future Addon System': 'Future Addon System',
    'Add Addon': 'Add Addon',
    'Installed Addons': 'Installed Addons',
    'Move addon up': 'Move addon up',
    'Move addon down': 'Move addon down',
    'Featured Addons': 'Featured Addons',
    'Permissions': 'Permissions',
    'Addons are third-party extensions. Only install addons from sources you trust.':
        'Addons are third-party extensions. Only install addons from sources you trust.',
    'Account': 'Account',
    'Profile': 'Profile',
    'Sign in': 'Sign in',
    'Open': 'Open',
    'Appearance': 'Appearance',
    'Theme mode': 'Theme mode',
    'System': 'System',
    'Dark': 'Dark',
    'Light': 'Light',
    'OLED': 'OLED',
    'Accent color': 'Accent color',
    'Poster card style': 'Poster card style',
    'Compact mode': 'Compact mode',
    'Reduce motion': 'Reduce motion',
    'Background blur intensity': 'Background blur intensity',
    'App language': 'App language',
    'Metadata language': 'Metadata language',
    'Subtitle preferred language': 'Subtitle preferred language',
    'Region / country preference': 'Region / country preference',
    'Metadata Providers': 'Metadata Providers',
    'Tracking Services': 'Tracking Services',
    'API Connections': 'API Connections',
    'Enable TMDB metadata': 'Enable TMDB metadata',
    'TMDB Read Access Token': 'TMDB Read Access Token',
    'Stored in secure platform storage. Do not commit secrets.':
        'Stored in secure platform storage. Do not commit secrets.',
    'TMDB language': 'TMDB language',
    'Synced from app and metadata language settings.':
        'Synced from app and metadata language settings.',
    'Controlled by Metadata language. App language only changes interface text.':
        'Controlled by Metadata language. App language only changes interface text.',
    'TMDB region': 'TMDB region',
    'TMDB connection': 'TMDB connection',
    'Configured': 'Configured',
    'Not configured': 'Not configured',
    'Test connection': 'Test connection',
    'AniList mobile client ID': 'AniList mobile client ID',
    'Used by Android and iOS WebView login.':
        'Used by Android and iOS WebView login.',
    'AniList desktop client ID': 'AniList desktop client ID',
    'Used by Windows, macOS, and Linux browser login.':
        'Used by Windows, macOS, and Linux browser login.',
    'AniList desktop callback port': 'AniList desktop callback port',
    'AniList mobile redirect': 'AniList mobile redirect',
    'AniList desktop redirect': 'AniList desktop redirect',
    'AniList account': 'AniList account',
    'AniList Settings': 'AniList Settings',
    'Open AniList profile content settings, list preferences, and MiruShin sync options.':
        'Open AniList profile content settings, list preferences, and MiruShin sync options.',
    'Connected': 'Connected',
    'Not connected': 'Not connected',
    'Login with AniList': 'Login with AniList',
    'AniList access token': 'AniList access token',
    'Open AniList': 'Open AniList',
    'Cancel': 'Cancel',
    'Web cannot listen on localhost. Open AniList, approve access, then paste the redirected URL or access_token here.':
        'Web cannot listen on localhost. Open AniList, approve access, then paste the redirected URL or access_token here.',
    'Paste a valid AniList access token.':
        'Paste a valid AniList access token.',
    'Sync anime lists': 'Sync anime lists',
    'Configure an AniList client ID first.':
        'Configure an AniList client ID first.',
    'AniList login canceled or failed.': 'AniList login canceled or failed.',
    'AniList Anime Lists': 'AniList Anime Lists',
    'Watching, planning, completed, paused, dropped, and repeating folders.':
        'Watching, planning, completed, paused, dropped, and repeating folders.',
    'Connect AniList in Settings to sync anime list folders.':
        'Connect AniList in Settings to sync anime list folders.',
    'Default Library page': 'Default Library page',
    'Opened first when that AniList folder has entries.':
        'Opened first when that AniList folder has entries.',
    'Watching': 'Watching',
    'Planning': 'Planning',
    'Completed': 'Completed',
    'Dropped': 'Dropped',
    'Paused': 'Paused',
    'Repeating': 'Repeating',
    'TVDB is the primary metadata source. TMDB fills in ratings and supplemental data.':
        'TVDB is the primary metadata source. TMDB fills in ratings and supplemental data.',
    'Configure a metadata source in Settings to load live data.':
        'Configure a metadata source in Settings to load live data.',
    'No live metadata yet': 'No live metadata yet',
    'No metadata source is configured yet. Add your credentials in Settings.':
        'No metadata source is configured yet. Add your credentials in Settings.',
    'Connect account': 'Connect account',
    'Disconnect account': 'Disconnect account',
    'Set as primary': 'Set as primary',
    'Set as backup': 'Set as backup',
    'Sync priority order': 'Sync priority order',
    'Last sync time': 'Last sync time',
    'Sync status': 'Sync status',
    'Conflict resolution strategy': 'Conflict resolution strategy',
    'Manual review': 'Manual review',
    'Local library location': 'Local library location',
    'Import library': 'Import library',
    'Export library': 'Export library',
    'Auto sync': 'Auto sync',
    'Enable addons': 'Enable addons',
    'Addon safety mode': 'Addon safety mode',
    'Trusted sources': 'Trusted sources',
    'Privacy & Security': 'Privacy & Security',
    'Local data only mode': 'Local data only mode',
    'Clear cache': 'Clear cache',
    'Clear metadata': 'Clear metadata',
    'Reset app': 'Reset app',
    'Addon safety warning': 'Addon safety warning',
    'Cache': 'Cache',
    'Metadata cache': 'Metadata cache',
    'Image cache': 'Image cache',
    'Cache limit': 'Cache limit',
    'Applies to the in-memory image cache.':
        'Applies to the in-memory image cache.',
    'Refreshes metadata cache on next load.':
        'Refreshes metadata cache on next load.',
    'Cache cleared': 'Cache cleared',
    'Metadata cache cleared': 'Metadata cache cleared',
    'About': 'About',
    'App version': 'App version',
    'Credits': 'Credits',
    'Legal notices': 'Legal notices',
    'This product uses the TMDB API but is not endorsed or certified by TMDB.':
        'This product uses the TMDB API but is not endorsed or certified by TMDB.',
    'English': 'English',
    'Russian': 'Russian',
    'Japanese': 'Japanese',
    'Movie': 'Movie',
    'Series type': 'Series',
    'Anime type': 'Anime',
    'Safe metadata-only foundation': 'Safe metadata-only foundation',
    'No player, streaming, scraping, or real addon execution is included.':
        'No player, streaming, scraping, or real addon execution is included.',
    'Read metadata': 'Read metadata',
    'Read local library': 'Read local library',
    'Suggest collections': 'Suggest collections',
    'Read tracking status': 'Read tracking status',
    'Enabled': 'Enabled',
    'Disabled': 'Disabled',
    'Local entries, watchlists, favorites, progress, and sync health.':
        'Local entries, watchlists, favorites, progress, and sync health.',
    'Review future sync conflicts before changing library state.':
        'Review future sync conflicts before changing library state.',
    'Safe backup and restore workflows.': 'Safe backup and restore workflows.',
    'Manual local entries only. No file scanning is implemented.':
        'Manual local entries only. No file scanning is implemented.',
    'Built as a polished Flutter foundation.':
        'Built as a polished Flutter foundation.',
    'No playback or subtitle logic is implemented.':
        'No playback or subtitle logic is implemented.',
    'No file scanning is implemented.': 'No file scanning is implemented.',
    'Trusted source controls are disabled until addons are implemented.':
        'Trusted source controls are disabled until addons are implemented.',
    'AniList sync failed': 'AniList sync failed',
    'No entries in this folder yet.': 'No entries in this folder yet.',
    'Added to Library': 'Added to Library',
    'Watch': 'Watch',
    'Watch unavailable': 'Watch unavailable',
    'Choose episode': 'Choose episode',
    'Pick an episode before searching sources.':
        'Pick an episode before searching sources.',
    'Tap an episode to open sources.': 'Tap an episode to open sources.',
    'Find sources': 'Find sources',
    'Refresh sources': 'Refresh sources',
    'Season': 'Season',
    'Episode': 'Episode',
    'Selected': 'Selected',
    'Ready': 'Ready',
    'In Library': 'In Library',
    'Marked as watched': 'Marked as watched',
    'Progress tracked locally': 'Progress tracked locally',
    'Removed from Library': 'Removed from Library',
    'Remove': 'Remove',
    'Library is empty': 'Library is empty',
    'Browse titles and add them to your library.':
        'Browse titles and add them to your library.',
    'Details unavailable': 'Details unavailable',
    'No installed addons': 'No installed addons',
    'Install a Sora addon to search sources.':
        'Install a Sora addon to search sources.',
    'Provider boundaries': 'Provider boundaries',
    'Local library': 'Local library',
    'AniList sync': 'AniList sync',
    'Safe actions': 'Safe actions',
    'No player logic': 'No player logic',
    'No streaming logic': 'No streaming logic',
    'No scraping logic': 'No scraping logic',
    'No metadata yet': 'No metadata yet',
    'Loaded': 'Loaded',
    'Page': 'Page',
    'Loading more': 'Loading more',
    'Infinite discovery': 'Infinite discovery',
    'All caught up': 'All caught up',
    'Load more': 'Load more',
    'Discovery is offline': 'Discovery is offline',
    'Duration': 'Duration',
    'Not in Library': 'Not in Library',
    'Overview': 'Overview',
    'Metadata, progress, and library actions only.':
        'Metadata, progress, and library actions only.',
    'Lists': 'Lists',
    'Current': 'Current',
    'Controls titles and overviews for TVDB and TMDB.':
        'Controls titles and overviews for TVDB and TMDB.',
  },
  'ru': <String, String>{
    'Board': 'Панель',
    'Discovery': 'Обзор',
    'Library': 'Библиотека',
    'Calendar': 'Календарь',
    'Addons': 'Аддоны',
    'Settings': 'Настройки',
    'More': 'Еще',
    'Switch Catalog Mode': 'Переключить каталог',
    'Switch to': 'Переключить на',
    'Current catalog': 'Текущий каталог',
    'Details': 'Детали',
    'Add to Library': 'В библиотеку',
    'Mark as Watched': 'Отметить просмотренным',
    'Continue Later': 'Продолжить позже',
    'Popular Movies': 'Популярные фильмы',
    'Popular Series': 'Популярные сериалы',
    'Popular Anime': 'Популярное аниме',
    'Trending Now': 'Сейчас в тренде',
    'Search media, genres, people, moods':
        'Поиск медиа, жанров, людей и настроений',
    'All': 'Все',
    'Watching': 'Смотрю',
    'Planning': 'Планирую',
    'Completed': 'Завершено',
    'Dropped': 'Брошено',
    'Paused': 'Пауза',
    'Repeating': 'Пересматриваю',
    'Default Library page': 'Страница библиотеки по умолчанию',
    'Opened first when that AniList folder has entries.':
        'Открывается первой, если в этой папке AniList есть записи.',
    'Movies': 'Фильмы',
    'Series': 'Сериалы',
    'Anime': 'Аниме',
    'Language': 'Язык',
    'Appearance': 'Внешний вид',
    'Theme mode': 'Тема',
    'System': 'Системная',
    'Dark': 'Темная',
    'Light': 'Светлая',
    'OLED': 'OLED',
    'English': 'Английский',
    'Russian': 'Русский',
    'Japanese': 'Японский',
    'Profile': 'Профиль',
    'Sign in': 'Войти',
    'Sign out': 'Выйти',
    'Open': 'Открыть',
    'Export': 'Экспорт',
    'Import': 'Импорт',
    'Export (MyAnimeList)': 'Экспорт (MyAnimeList)',
    'Export Shikimori': 'Экспорт Shikimori',
    'Saves a local AniList library export in MyAnimeList XML format.':
        'Сохраняет локальный экспорт библиотеки AniList в формате MyAnimeList XML.',
    'Saves a local AniList library export in Shikimori JSON format.':
        'Сохраняет локальный экспорт библиотеки AniList в формате Shikimori JSON.',
    'Activities': 'Активности',
    'Favourites': 'Избранное',
    'Feed': 'Лента',
    'Social': 'Соцсеть',
    'Statistics': 'Статистика',
    'Reviews': 'Обзоры',
    'AniList Settings': 'Настройки AniList',
    'Open AniList profile content settings, list preferences, and MiruShin sync options.':
        'Открыть настройки контента профиля AniList, списков и синхронизации MiruShin.',
    'Profile is only available while the AniList catalog is active.':
        'Профиль доступен только при активном каталоге AniList.',
    'AniList not connected': 'AniList не подключён',
    'Sign in to open your AnimeShin-style AniList profile, social pages, exports, and content settings.':
        'Войдите, чтобы открыть профиль AniList в стиле AnimeShin, социальные страницы, экспорт и настройки контента.',
    'Activities, favourites, feed, social, statistics, reviews, exports, and AniList content settings.':
        'Активности, избранное, лента, соцсеть, статистика, обзоры, экспорт и настройки контента AniList.',
    'AniList user profile.': 'Профиль пользователя AniList.',
    'User not found': 'Пользователь не найден',
    'AniList did not return a profile for this user.':
        'AniList не вернул профиль этого пользователя.',
    'Recent Activity': 'Недавняя активность',
    'Profile activity from AniList.': 'Активность профиля из AniList.',
    'Recent AniList activity from your profile.':
        'Недавняя активность из вашего профиля AniList.',
    'Recent public activity, using AnimeShin feed defaults.':
        'Недавняя публичная активность с настройками ленты AnimeShin по умолчанию.',
    'Favourite anime, manga, characters, staff, and studios.':
        'Избранные аниме, манга, персонажи, сотрудники и студии.',
    'Following, followers, forum threads, and comments.':
        'Подписки, подписчики, темы форума и комментарии.',
    'Anime and manga totals from your AniList account.':
        'Итоги по аниме и манге из вашего аккаунта AniList.',
    'Recent reviews published on AniList.':
        'Недавние обзоры, опубликованные на AniList.',
    'Your profile activity and tracking timeline.':
        'Активность профиля и таймлайн отслеживания.',
    'Anime, manga, characters, staff, and studios.':
        'Аниме, манга, персонажи, сотрудники и студии.',
    'People you follow on AniList.': 'Люди, на которых вы подписаны в AniList.',
    'Followers and following lists.': 'Списки подписчиков и подписок.',
    'Anime and manga account totals.': 'Итоги аккаунта по аниме и манге.',
    'Recent AniList reviews.': 'Недавние обзоры AniList.',
    'AnimeShin content and list preferences.':
        'Настройки контента и списков AnimeShin.',
    'New Post': 'Новый пост',
    'Post': 'Опубликовать',
    'Share an AniList status update...': 'Поделитесь статусом в AniList...',
    'Failed to post': 'Не удалось опубликовать',
    'Nothing here yet': 'Здесь пока пусто',
    'AniList activity will appear here once something is posted or tracked.':
        'Активность AniList появится здесь после публикаций или обновления прогресса.',
    'Unknown time': 'Неизвестное время',
    'media': 'медиа',
    'Open on AniList': 'Открыть в AniList',
    'Open AniList': 'Открыть AniList',
    'Subscribe': 'Подписаться',
    'Unsubscribe': 'Отписаться',
    'AniList action failed': 'Действие AniList не удалось',
    'Following': 'Подписки',
    'Followers': 'Подписчики',
    'Threads': 'Темы',
    'Comments': 'Комментарии',
    'No threads yet': 'Тем пока нет',
    'AniList forum threads from this user will appear here.':
        'Темы форума AniList этого пользователя появятся здесь.',
    'No comments yet': 'Комментариев пока нет',
    'AniList forum comments from this user will appear here.':
        'Комментарии форума AniList этого пользователя появятся здесь.',
    'Locked': 'Заблокировано',
    'Anime count': 'Всего аниме',
    'Minutes watched': 'Минут просмотрено',
    'Manga count': 'Всего манги',
    'Chapters read': 'Глав прочитано',
    'Total Anime': 'Всего аниме',
    'Total Manga': 'Всего манги',
    'Episodes Watched': 'Эпизодов просмотрено',
    'Chapters Read': 'Глав прочитано',
    'Days Watched': 'Дней просмотра',
    'Volumes Read': 'Томов прочитано',
    'Mean Score': 'Средняя оценка',
    'Standard Deviation': 'Стандартное отклонение',
    'Score Distribution': 'Распределение оценок',
    'Titles': 'Тайтлы',
    'Episodes / Chapters': 'Эпизоды / главы',
    'Minutes': 'Минуты',
    'Chapters': 'Главы',
    'Formats': 'Форматы',
    'Statuses': 'Статусы',
    'Countries': 'Страны',
    'No data available yet.': 'Данных пока нет.',
    'No reviews yet': 'Обзоров пока нет',
    'Your AniList reviews will appear here.':
        'Ваши обзоры AniList появятся здесь.',
    'Newest': 'Сначала новые',
    'Oldest': 'Сначала старые',
    'Highest Rated': 'С высоким рейтингом',
    'Lowest Rated': 'С низким рейтингом',
    'Review of': 'Обзор',
    'Sign in to AniList to use this profile section.':
        'Войдите в AniList, чтобы использовать этот раздел профиля.',
    'This page becomes available after you sign in to AniList.':
        'Эта страница станет доступна после входа в AniList.',
    'Something went wrong': 'Что-то пошло не так',
    'Your AniList profile hub inside MiruShin.':
        'Ваш центр профиля AniList внутри MiruShin.',
    'Media': 'Медиа',
    'Title language': 'Язык названий',
    'Controls AniList media title display throughout the app.':
        'Управляет отображением названий AniList во всём приложении.',
    'Character & Staff Names': 'Имена персонажей и сотрудников',
    'Activity Merge Time': 'Объединение активности',
    '18+ Content': 'Контент 18+',
    'Airing Anime Notifications': 'Уведомления о выходе аниме',
    'Lists': 'Списки',
    'Scoring System': 'Система оценок',
    'Default Site List Sort': 'Сортировка списков на сайте',
    'Split Completed Anime': 'Разделять завершённые аниме',
    'Split Completed Manga': 'Разделять завершённую мангу',
    'Advanced Scoring': 'Расширенные оценки',
    'Advanced Score Labels': 'Названия расширенных оценок',
    'These labels are saved back to AniList for advanced score slots.':
        'Эти названия сохраняются в AniList для расширенных оценок.',
    'Limit Messages': 'Ограничить сообщения',
    'Only users you follow can message you.':
        'Писать вам смогут только пользователи, на которых вы подписаны.',
    'Auto track progress': 'Автоотслеживание прогресса',
    'Update AniList when 85% of an episode is watched.':
        'Обновлять AniList, когда просмотрено 85% эпизода.',
    'Saving automatically...': 'Автосохранение...',
    'Changes save automatically': 'Изменения сохраняются автоматически',
    'Autosave failed': 'Автосохранение не удалось',
    'Never': 'Никогда',
    '30 Minutes': '30 минут',
    '1 Hour': '1 час',
    '2 Hours': '2 часа',
    '3 Hours': '3 часа',
    '6 Hours': '6 часов',
    '12 Hours': '12 часов',
    '1 Day': '1 день',
    '2 Days': '2 дня',
    '3 Days': '3 дня',
    '1 Week': '1 неделя',
    '2 Weeks': '2 недели',
    'Always': 'Всегда',
    'Romaji': 'Ромадзи',
    'Native': 'Оригинальный',
    'Russian (Shikimori)': 'Русский (Shikimori)',
    'Romaji, Western Order': 'Ромадзи, западный порядок',
    '100-point': '100-балльная',
    '10-point decimal': '10-балльная с десятыми',
    '10-point': '10-балльная',
    '5-star': '5 звёзд',
    '3-point': '3 смайла',
    'Title': 'Название',
    'Score': 'Оценка',
    'Last Updated': 'Последнее обновление',
    'Last Added': 'Последнее добавление',
    'Please sign in to export': 'Войдите, чтобы выполнить экспорт',
    'Exporting...': 'Экспорт...',
    'Nothing to export': 'Нечего экспортировать',
    'Export file shared': 'Файл экспорта отправлен',
    'Exported to': 'Экспортировано в',
    'Export timeout. Check connection and try again.':
        'Тайм-аут экспорта. Проверьте соединение и попробуйте снова.',
    'Export failed': 'Экспорт не удался',
    'App language': 'Язык приложения',
    'Metadata language': 'Язык метаданных',
    'Subtitle preferred language': 'Предпочитаемый язык субтитров',
    'Region / country preference': 'Регион / страна',
    'Controls titles and overviews from TMDB.':
        'Управляет названиями и описаниями из TMDB.',
    'Used by TMDB release calendars and localization.':
        'Используется календарями релизов TMDB и локализацией.',
  },
  'ja': <String, String>{
    'Board': 'ボード',
    'Discovery': 'ディスカバリー',
    'Library': 'ライブラリ',
    'Calendar': 'カレンダー',
    'Addons': 'アドオン',
    'Settings': '設定',
    'More': 'その他',
    'Switch Catalog Mode': 'カタログを切り替え',
    'Switch to': '切り替え先',
    'Current catalog': '現在のカタログ',
    'Details': '詳細',
    'Add to Library': 'ライブラリに追加',
    'Mark as Watched': '視聴済みにする',
    'Continue Later': 'あとで続ける',
    'Popular Movies': '人気の映画',
    'Popular Series': '人気のシリーズ',
    'Popular Anime': '人気のアニメ',
    'Trending Now': 'トレンド',
    'Search media, genres, people, moods': 'メディア、ジャンル、人物、ムードを検索',
    'All': 'すべて',
    'Movies': '映画',
    'Series': 'シリーズ',
    'Anime': 'アニメ',
    'Language': '言語',
    'Appearance': '外観',
    'Theme mode': 'テーマ',
    'System': 'システム',
    'Dark': 'ダーク',
    'Light': 'ライト',
    'OLED': 'OLED',
    'English': '英語',
    'Russian': 'ロシア語',
    'Japanese': '日本語',
    'Profile': 'プロフィール',
    'Sign in': 'サインイン',
    'Sign out': 'サインアウト',
    'Open': '開く',
    'Export': 'エクスポート',
    'Import': 'インポート',
    'Export (MyAnimeList)': 'エクスポート (MyAnimeList)',
    'Export Shikimori': 'Shikimoriへエクスポート',
    'Saves a local AniList library export in MyAnimeList XML format.':
        'AniListライブラリをMyAnimeList XML形式でローカルに保存します。',
    'Saves a local AniList library export in Shikimori JSON format.':
        'AniListライブラリをShikimori JSON形式でローカルに保存します。',
    'Activities': 'アクティビティ',
    'Favourites': 'お気に入り',
    'Feed': 'フィード',
    'Social': 'ソーシャル',
    'Statistics': '統計',
    'Reviews': 'レビュー',
    'AniList Settings': 'AniList設定',
    'Open AniList profile content settings, list preferences, and MiruShin sync options.':
        'AniListプロフィールのコンテンツ設定、リスト設定、MiruShin同期オプションを開きます。',
    'Profile is only available while the AniList catalog is active.':
        'プロフィールはAniListカタログが有効なときだけ利用できます。',
    'AniList not connected': 'AniList未接続',
    'Sign in to open your AnimeShin-style AniList profile, social pages, exports, and content settings.':
        'サインインすると、AnimeShin風のAniListプロフィール、ソーシャル、エクスポート、コンテンツ設定を開けます。',
    'Activities, favourites, feed, social, statistics, reviews, exports, and AniList content settings.':
        'アクティビティ、お気に入り、フィード、ソーシャル、統計、レビュー、エクスポート、AniListコンテンツ設定。',
    'AniList user profile.': 'AniListユーザープロフィール。',
    'User not found': 'ユーザーが見つかりません',
    'AniList did not return a profile for this user.':
        'AniListからこのユーザーのプロフィールが返されませんでした。',
    'Recent Activity': '最近のアクティビティ',
    'Profile activity from AniList.': 'AniListのプロフィールアクティビティ。',
    'Recent AniList activity from your profile.':
        'あなたのプロフィールの最近のAniListアクティビティ。',
    'Recent public activity, using AnimeShin feed defaults.':
        'AnimeShinの既定フィード設定で最近の公開アクティビティを表示します。',
    'Favourite anime, manga, characters, staff, and studios.':
        'お気に入りのアニメ、マンガ、キャラクター、スタッフ、スタジオ。',
    'Following, followers, forum threads, and comments.':
        'フォロー中、フォロワー、フォーラムスレッド、コメント。',
    'Anime and manga totals from your AniList account.':
        'AniListアカウントのアニメとマンガの合計。',
    'Recent reviews published on AniList.': 'AniListで公開された最近のレビュー。',
    'Your profile activity and tracking timeline.': 'プロフィールアクティビティと追跡タイムライン。',
    'Anime, manga, characters, staff, and studios.':
        'アニメ、マンガ、キャラクター、スタッフ、スタジオ。',
    'People you follow on AniList.': 'AniListでフォローしているユーザー。',
    'Followers and following lists.': 'フォロワーとフォロー中のリスト。',
    'Anime and manga account totals.': 'アカウントのアニメとマンガの合計。',
    'Recent AniList reviews.': '最近のAniListレビュー。',
    'AnimeShin content and list preferences.': 'AnimeShinのコンテンツとリスト設定。',
    'New Post': '新規投稿',
    'Post': '投稿',
    'Share an AniList status update...': 'AniListのステータスを投稿...',
    'Failed to post': '投稿に失敗しました',
    'Nothing here yet': 'まだ何もありません',
    'AniList activity will appear here once something is posted or tracked.':
        '投稿または追跡が行われると、AniListアクティビティがここに表示されます。',
    'Unknown time': '時刻不明',
    'media': 'メディア',
    'Open on AniList': 'AniListで開く',
    'Open AniList': 'AniListを開く',
    'Subscribe': '購読',
    'Unsubscribe': '購読解除',
    'AniList action failed': 'AniList操作に失敗しました',
    'Following': 'フォロー中',
    'Followers': 'フォロワー',
    'Threads': 'スレッド',
    'Comments': 'コメント',
    'No threads yet': 'スレッドはまだありません',
    'AniList forum threads from this user will appear here.':
        'このユーザーのAniListフォーラムスレッドがここに表示されます。',
    'No comments yet': 'コメントはまだありません',
    'AniList forum comments from this user will appear here.':
        'このユーザーのAniListフォーラムコメントがここに表示されます。',
    'Locked': 'ロック中',
    'Anime count': 'アニメ数',
    'Minutes watched': '視聴分数',
    'Manga count': 'マンガ数',
    'Chapters read': '読了チャプター',
    'Total Anime': 'アニメ合計',
    'Total Manga': 'マンガ合計',
    'Episodes Watched': '視聴エピソード',
    'Chapters Read': '読了チャプター',
    'Days Watched': '視聴日数',
    'Volumes Read': '読了巻数',
    'Mean Score': '平均スコア',
    'Standard Deviation': '標準偏差',
    'Score Distribution': 'スコア分布',
    'Titles': 'タイトル',
    'Episodes / Chapters': 'エピソード / チャプター',
    'Minutes': '分',
    'Chapters': 'チャプター',
    'Formats': '形式',
    'Statuses': 'ステータス',
    'Countries': '国',
    'No data available yet.': 'データはまだありません。',
    'No reviews yet': 'レビューはまだありません',
    'Your AniList reviews will appear here.': 'あなたのAniListレビューがここに表示されます。',
    'Newest': '新しい順',
    'Oldest': '古い順',
    'Highest Rated': '高評価順',
    'Lowest Rated': '低評価順',
    'Review of': 'レビュー',
    'Sign in to AniList to use this profile section.':
        'このプロフィールセクションを使うにはAniListにサインインしてください。',
    'This page becomes available after you sign in to AniList.':
        'AniListにサインインするとこのページを利用できます。',
    'Something went wrong': '問題が発生しました',
    'Your AniList profile hub inside MiruShin.':
        'MiruShin内のあなたのAniListプロフィールハブ。',
    'Media': 'メディア',
    'Title language': 'タイトル言語',
    'Controls AniList media title display throughout the app.':
        'アプリ全体のAniListメディアタイトル表示を制御します。',
    'Character & Staff Names': 'キャラクター・スタッフ名',
    'Activity Merge Time': 'アクティビティ統合時間',
    '18+ Content': '18+コンテンツ',
    'Airing Anime Notifications': '放送中アニメ通知',
    'Lists': 'リスト',
    'Scoring System': 'スコア形式',
    'Default Site List Sort': 'サイトリストの既定ソート',
    'Split Completed Anime': '完了アニメを分割',
    'Split Completed Manga': '完了マンガを分割',
    'Advanced Scoring': '詳細スコア',
    'Advanced Score Labels': '詳細スコアラベル',
    'These labels are saved back to AniList for advanced score slots.':
        'これらのラベルは詳細スコア枠としてAniListに保存されます。',
    'Limit Messages': 'メッセージを制限',
    'Only users you follow can message you.': 'フォローしているユーザーだけがメッセージを送れます。',
    'Auto track progress': '進捗を自動追跡',
    'Update AniList when 85% of an episode is watched.':
        'エピソードを85%視聴したらAniListを更新します。',
    'Saving automatically...': '自動保存中...',
    'Changes save automatically': '変更は自動保存されます',
    'Autosave failed': '自動保存に失敗しました',
    'Never': 'なし',
    '30 Minutes': '30分',
    '1 Hour': '1時間',
    '2 Hours': '2時間',
    '3 Hours': '3時間',
    '6 Hours': '6時間',
    '12 Hours': '12時間',
    '1 Day': '1日',
    '2 Days': '2日',
    '3 Days': '3日',
    '1 Week': '1週間',
    '2 Weeks': '2週間',
    'Always': '常に',
    'Romaji': 'ローマ字',
    'Native': 'ネイティブ',
    'Russian (Shikimori)': 'ロシア語 (Shikimori)',
    'Romaji, Western Order': 'ローマ字・西洋順',
    '100-point': '100点',
    '10-point decimal': '10点（小数）',
    '10-point': '10点',
    '5-star': '5つ星',
    '3-point': '3スマイル',
    'Title': 'タイトル',
    'Score': 'スコア',
    'Last Updated': '最終更新',
    'Last Added': '最終追加',
    'Please sign in to export': 'エクスポートするにはサインインしてください',
    'Exporting...': 'エクスポート中...',
    'Nothing to export': 'エクスポートするものがありません',
    'Export file shared': 'エクスポートファイルを共有しました',
    'Exported to': 'エクスポート先',
    'Export timeout. Check connection and try again.':
        'エクスポートがタイムアウトしました。接続を確認して再試行してください。',
    'Export failed': 'エクスポート失敗',
    'App language': 'アプリの言語',
    'Metadata language': 'メタデータ言語',
    'Subtitle preferred language': '字幕の優先言語',
    'Region / country preference': '地域 / 国の設定',
    'Controls titles and overviews from TMDB.': 'TMDBのタイトルと概要の言語を制御します。',
    'Used by TMDB release calendars and localization.':
        'TMDBのリリースカレンダーとローカライズに使用されます。',
  },
};
